import React from "react";
import { Layout } from "antd";
import "./globals.css";
import { SideBar } from "@/components/elements/SideBar";

const { Content } = Layout;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html>
      <body>
        <Layout>
          <SideBar>{children}</SideBar>
        </Layout>
      </body>
    </html>
  );
};

export default RootLayout;
